"""
3_VAPT_Findings.py — Rule-based findings from session assessment evidence.
"""

import streamlit as st
from html import escape
from theme import apply_theme, sidebar_brand, get_active_colors, notification_center, SEVERITY_ORDER, logout_button
from authcheck import require_auth
from workspace import t

st.set_page_config(page_title="SecMate — VAPT Findings", layout="wide")
require_auth()
COLORS = get_active_colors()
apply_theme()
sidebar_brand()
logout_button()
notification_center()

st.markdown(
    f"<div class='page-kicker'>VULNERABILITY MANAGEMENT</div>"
    f"<div class='page-title'>{t('findings_title')}</div>"
    f"<div class='page-subtitle'>{t('findings_subtitle')} Prioritize, assign, and retest validated exposure.</div>",
    unsafe_allow_html=True,
)


def get_findings():
    history = st.session_state.get("assessment_history", [])
    real_findings = []
    for run in history:
        real_findings.extend(run.get("findings", []))
    return real_findings


findings = get_findings()
has_real_findings = bool(st.session_state.get("assessment_history"))
if has_real_findings and findings:
    st.info("Showing findings generated from launched red-team assessments in this session.")
elif has_real_findings:
    st.success("No findings were generated by the completed assessments in this session.")
else:
    st.markdown(f'<div class="demo-banner">No assessment findings yet. SecMate will populate this workspace only from evidence produced by your authorized runs.</div>', unsafe_allow_html=True)

summary_cols = st.columns(5)
for col, severity in zip(summary_cols, SEVERITY_ORDER):
    count = sum(f.get("severity") == severity for f in findings)
    with col:
        st.markdown(f'<div class="metric-card"><div class="label">{severity.title()}</div><div class="value" style="color:{COLORS[severity]};">{count}</div></div>', unsafe_allow_html=True)

st.markdown("<div style='height:16px;'></div>", unsafe_allow_html=True)

# --- Filters ---
f0, f1, f2, f3 = st.columns([1.4, 1, 1, 1])
with f0:
    search = st.text_input("Search findings", placeholder="ID, title, category, target")
with f1:
    sev_filter = st.multiselect("Severity", SEVERITY_ORDER, default=SEVERITY_ORDER)
with f2:
    status_filter = st.multiselect("Status", ["open", "acknowledged", "resolved"], default=["open", "acknowledged", "resolved"])
with f3:
    targets = sorted({f["target"] for f in findings})
    target_filter = st.multiselect("Target", targets, default=targets)

st.markdown("<div style='height:10px;'></div>", unsafe_allow_html=True)

visible = [f for f in findings if f["severity"] in sev_filter and f["status"] in status_filter and f["target"] in target_filter and search.lower() in f"{f['id']} {f['title']} {f['category']} {f['target']}".lower()]
visible.sort(key=lambda f: SEVERITY_ORDER.index(f["severity"]))

sev_hex = {"critical": COLORS["critical"], "high": COLORS["high"], "medium": COLORS["medium"], "low": COLORS["low"], "info": COLORS["info"]}

if not visible:
    st.markdown(f"<div style='color:{COLORS['text_secondary']}; padding:20px 0;'>No findings match the selected filters.</div>", unsafe_allow_html=True)

for f in visible:
    with st.container():
        st.markdown(
            f"""
            <div class="finding-row" style="--sev-color:{sev_hex[f['severity']]};">
                <div style="display:flex; justify-content:space-between; align-items:flex-start;">
                    <div>
                        <span class="badge badge-{f['severity']}">{escape(str(f['severity']).upper())}</span>
                        <span class="finding-title" style="margin-left:8px;">{escape(str(f['title']))}</span>
                    </div>
                    <span style="font-family:'JetBrains Mono',monospace; font-size:11.5px; color:{COLORS['text_secondary']};">{escape(str(f['id']))}</span>
                </div>
                <div class="finding-meta">{escape(str(f['category']))} · {escape(str(f['target']))} · {escape(str(f['status']).title())} · Rule {escape(str(f['rule']))}</div>
            </div>
            """,
            unsafe_allow_html=True,
        )
        with st.expander("View evidence & remediation"):
            st.markdown(f"**Evidence**  \n{f['evidence']}")
            st.markdown(f"**Suggested remediation**  \n{f['remediation']}")
            a1, a2, a3 = st.columns(3)
            a1.button("Assign owner", key=f"assign_{f['id']}", use_container_width=True, disabled=True, help="Available when persistent users and finding workflow are connected.")
            a2.button("Create ticket", key=f"ticket_{f['id']}", use_container_width=True, disabled=True, help="Connect Jira or GitHub from Integrations.")
            if a3.button("Retest finding", key=f"retest_{f['id']}", use_container_width=True):
                st.info("Open New Assessment and select the same target and technique category to validate remediation.")
