import time

import streamlit as st

from backend_client import BackendUnavailable, backend_available, create_run, get_preflight, get_run_evidence, list_targets
from data import PREFLIGHT, TARGETS
from ui import configure_page, target_by_name


configure_page(
    "New assessment",
    "Configure a red-team run. Preflight must clear before the run can start.",
)

if "resolved_gates" not in st.session_state:
    st.session_state.resolved_gates = {}
if "run_started" not in st.session_state:
    st.session_state.run_started = False

try:
    BACKEND_ON = backend_available()
    TARGET_DATA = list_targets() if BACKEND_ON else TARGETS
except (BackendUnavailable, Exception):
    BACKEND_ON = False
    TARGET_DATA = TARGETS

if BACKEND_ON:
    st.success("Backend connected. Runs can use FastAPI and optional Qwen/Ollama generation.")
else:
    st.warning("Backend is not running. This page will use local simulated assessment flow.")

left, right = st.columns([3, 2])

with left:
    target_name = st.selectbox("Project target", [target["name"] for target in TARGET_DATA])
    tier = st.radio("Assessment tier", ["Tier 1 - PR", "Tier 2 - deep", "Tier 3 - compliance"], horizontal=True)
    target = target_by_name(TARGET_DATA, target_name)
    use_qwen = st.checkbox("Use Qwen/Ollama attacker model when backend is available", value=False)
    st.markdown("### Vulnerability scope")
    for vuln, value in target["classes"].items():
        st.progress(value / 100, text=f"{vuln}: current pass rate {value}%")

with right:
    st.markdown("### Preflight gates")
    blocking = []
    if BACKEND_ON:
        try:
            backend_preflight = get_preflight(target["id"])
            gates = backend_preflight.get("gates", [])
        except Exception as exc:
            st.warning(f"Could not load backend preflight, using local gates: {exc}")
            gates = PREFLIGHT
    else:
        gates = PREFLIGHT

    for gate in gates:
        state = st.session_state.resolved_gates.get(gate["key"], gate["state"])
        if state != "pass":
            blocking.append(gate)
        title = gate.get("title") or gate.get("t")
        description = gate.get("description") or gate.get("d")
        why = gate.get("why") or gate.get("gap")
        key = gate.get("key") or gate.get("k")
        st.markdown(
            f"""
            <div class="gate {state}">
              <b>{title}</b>
              <p style="margin:.2rem 0;color:#5a6472">{description}</p>
              <small>{why}</small>
            </div>
            """,
            unsafe_allow_html=True,
        )
        if state != "pass":
            if st.button(f"Mark resolved: {title}", key=f"resolve_{key}", use_container_width=True):
                st.session_state.resolved_gates[key] = "pass"
                st.rerun()

    if blocking:
        st.error(f"Blocked by: {blocking[0]['title']}. Running now would create false assurance.")
    else:
        if st.button("Start assessment", type="primary", use_container_width=True):
            st.session_state.run_started = True

if st.session_state.run_started:
    st.divider()
    st.subheader("Run confirmation")
    with st.container(border=True):
        st.write(f"**Project:** {target_name}")
        st.write(f"**Tier:** {tier}")
        st.write(f"**Backend:** {'FastAPI connected' if BACKEND_ON else 'local simulation'}")
        st.write(f"**Qwen/Ollama:** {'enabled' if use_qwen and BACKEND_ON else 'disabled'}")
        st.write("**Evidence required:** tool calls with `input_parameters` and `output`.")
        confirm = st.button("Confirm and run demo assessment", type="primary")
    if confirm:
        st.session_state.run_started = False
        if BACKEND_ON:
            tier_map = {
                "Tier 1 - PR": "ci",
                "Tier 2 - deep": "deep",
                "Tier 3 - compliance": "framework",
            }
            with st.status("Running backend red-team assessment", expanded=True) as status:
                run = create_run(target["id"], tier=tier_map.get(tier, "deep"), use_model=use_qwen)
                for event in run.get("events", []):
                    st.write(event)
                    time.sleep(0.2)
                status.update(label=f"Run {run['state']}", state="complete" if run["state"] == "complete" else "error")
            st.json(run)
            if run.get("state") == "complete":
                evidence = get_run_evidence(run["id"])
                st.metric("Weighted pass rate", f"{run.get('pass_rate', 0)}%")
                st.subheader("Evidence generated by backend")
                st.json(evidence)
            else:
                st.error(run.get("summary", "Run did not complete."))
        else:
            with st.status("Running local simulated red-team assessment", expanded=True) as status:
                for event in [
                    "Admission token accepted",
                    "Corpus version locked",
                    "Simulator generating action-layer attacks",
                    "Target returned tool calls with parameters and outputs",
                    "Evaluator scoring complete",
                    "Regression F-201 failed again as F-231",
                ]:
                    st.write(event)
                    time.sleep(0.35)
                status.update(label="Assessment complete", state="complete")
            st.error("Regression found: previously closed F-201 failed again through a different prompt path.")
            st.metric("Weighted pass rate", "74%", "-4 points")
